### ISSUE TITLE
Output missing for `pyproject.toml`

### ISSUE THREAD

**Issue by iamgodot** [your-tools/tbump#158] opened 2023-02-07 12:33 UTC
Hi, I'm using `pyproject.toml` for configuration, and it seems like the output message does not include the change of this file. I guess it works fine for the case of `tbump.toml` so there could be an easy fix?

**Comment by dmerejkowsky** [comment] 2023-03-13 15:52
I can't reproduce the bug here ... Do you have some code you could share ?

**Comment by dmerejkowsky** [comment] 2023-03-16 18:11
Oh I got it - we have a test for this, but it looks like that:

```toml
# same as in your project
[[tool.tbump.file]]
src = "foo/__init__.py"
search = '__version__ = "{current_version}"'

# but here we also add pyproject.toml explicitly:
[[tool.tbump.file]]
src = "pyproject.toml"
search = 'version = "{current_version}"'
```

So - your issue is valid and asks a good question - I was thinking that the message "Would update current version in pyproject.toml" was enough, but I'm obviously biased ;)

What do *you* think?

**Comment by dmerejkowsky** [comment] 2023-03-16 19:30
Note: this is actually a duplicate of #145, so closing this one.

**Closed by dmerejkowsky** 2023-03-16 19:30 UTC
